SchoolSystem/Models/Materia.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SchoolSystem.Models
{
    public class Materia
    {
        [Key]
        [ScaffoldColumn(false)]
        [Display(Name = "Código")]
        public int IdMateria { get; set; }
        [Required]
        [Display(Name = "Nome")]
        public string NomeMateria { get; set; }
    }
}

SchoolSystem/Controllers/MateriasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolSystem.Models;

namespace SchoolSystem.Controllers
{
    public class MateriasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Materias
        // Entity Framework, retorna todas as matérias
        public ActionResult Index()
        {
            return View(db.Materias.ToList());
        }
        // Adiciona a matéria
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdMateria,NomeMateria")] Materia materia)
        {
            if (ModelState.IsValid)
            {
                db.Materias.Add(materia);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolSystem/Views/Materias/Create.cshtml
@model SchoolSystem.Models.Materia

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Materia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomeMateria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeMateria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeMateria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolSystem/Views/Materias/Delete.cshtml
@model SchoolSystem.Models.Materia

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Materia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeMateria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeMateria)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SchoolSystem/Views/Materias/Details.cshtml
@model SchoolSystem.Models.Materia

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Materia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeMateria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeMateria)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdMateria }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SchoolSystem/Views/Materias/Edit.cshtml
@model SchoolSystem.Models.Materia

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Materia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomeMateria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeMateria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeMateria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolSystem/Views/Materias/Index.cshtml
@model IEnumerable<SchoolSystem.Models.Materia>

@{
    ViewBag.Title = "Index";
}


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">CADASTRO DE MATÉRIAS</h6>
    </div>
    <div class="card-body">
        <form action="@Url.Action("Create", "Materias")" method="post" class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            @Html.AntiForgeryToken()
            <div class="input-group">

                <input class="form-control" name="NomeMateria" id="NomeMateria" type="text" placeholder="Digite a matéria...">
                &nbsp;
                &nbsp;
                <input style="color:white" class="btn btn-success btn-icon-split" type="submit" value=" INSERIR MATÉRIAS ">

            </div>
        </form>
        <BR /><BR />
        <div class="table-responsive">

            <!-- Topbar Search -->


            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th># CÓDIGO</th>
                    <th>PROFESSOR</th>


                </tr>
                </thead>
                <tfoot>

                </tfoot>
                <tbody>
                @foreach (var item in Model)
                {

                    <tr>
                        <td>@item.IdMateria</td>
                        <td>@item.NomeMateria</td>

                    </tr>

                }
                </tbody>
            </table>
        </div>
    </div>
</div>