SchoolSystem/Models/Professor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SchoolSystem.Models
{
    public class Professor
    {
        [Key]
        [ScaffoldColumn(false)]
        [Display(Name = "Código")]
        public int IdProfessor { get; set; }
        [Required]
        [Display(Name = "Nome")]
        public string NomeProfessor { get; set; }
    }
}

SchoolSystem/Controllers/ProfessorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolSystem.Models;

namespace SchoolSystem.Controllers
{
    public class ProfessorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Professors
        // Entity Framework retorna todos os professores
        public ActionResult Index()
        {
            return View(db.Professores.ToList());
        }
        // Adiciona os professores
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdProfessor,NomeProfessor")] Professor professor)
        {
            if (ModelState.IsValid)
            {
                db.Professores.Add(professor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolSystem/Views/Professors/Create.cshtml
@model SchoolSystem.Models.Professor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Professor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomeProfessor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeProfessor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeProfessor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolSystem/Views/Professors/Delete.cshtml
@model SchoolSystem.Models.Professor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Professor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeProfessor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeProfessor)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SchoolSystem/Views/Professors/Details.cshtml
@model SchoolSystem.Models.Professor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Professor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeProfessor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeProfessor)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdProfessor }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SchoolSystem/Views/Professors/Edit.cshtml
@model SchoolSystem.Models.Professor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Professor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomeProfessor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeProfessor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeProfessor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolSystem/Views/Professors/Index.cshtml
@model IEnumerable<SchoolSystem.Models.Professor>

@{
    ViewBag.Title = "Index";
}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">CADASTRO DE PROFESSORES</h6>
    </div>
    <div class="card-body">
        <form action="@Url.Action("Create", "Professors")" method="post" class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            @Html.AntiForgeryToken()
            <div class="input-group">

                <input class="form-control" name="NomeProfessor" id="NomeProfessor" type="text" placeholder="Digite o nome...">
                &nbsp;
                &nbsp;
                <input style="color:white" class="btn btn-success btn-icon-split" type="submit" value=" INSERIR PROFESSOR ">

            </div>
        </form>
        <BR /><BR />
        <div class="table-responsive">

            <!-- Topbar Search -->


            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th># CÓDIGO</th>
                        <th>PROFESSOR</th>


                    </tr>
                </thead>
                <tfoot>

                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>@item.IdProfessor</td>
                            <td>@item.NomeProfessor</td>

                        </tr>

                    }
                </tbody>
            </table>
        </div>
    </div>
</div>